services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
      - ./ollama:/modelfiles
    environment:
      - OLLAMA_KEEP_ALIVE=-1
    entrypoint: >
      sh -c "
      ollama serve &
      sleep 5 &&
      ollama create mistral-finance-ft -f /modelfiles/Modelfile &&
      ollama run mistral-finance-ft 'ready' &&
      tail -f /dev/null
      "

  fastapi:
    build: ./fastapi_app
    depends_on:
      - qdrant
      - ollama
    ports:
      - "8000:8000"
    env_file:
    - .env
    volumes:
    - ./fastapi_app:/app

volumes:
  qdrant_data:
  ollama_models:
